version: "3"

tasks:
  test1:
    cmds:
      - go run cmd/main.go -f=input/testdata1.txt

  part1:
    cmds:
      - go run cmd/main.go -f=input/data.txt

  test2:
    cmds:
      - go run cmd/main.go -s -f=input/testdata2.txt

  part2:
    cmds:
      - go run cmd/main.go -s -f=input/data.txt
