version: "3"

tasks:
  test1:
    cmds:
      - go run cmd/part1/main.go input/testdata1.txt

  part1:
    cmds:
      - go run cmd/part1/main.go input/data.txt

  test2:
    cmds:
      - go run cmd/part2/main.go input/testdata2.txt

  part2:
    cmds:
      - go run cmd/part2/main.go input/data.txt
