version: "3"

tasks:
  test:
    cmds:
      - go test ./...

  sample:
    cmds:
      - go run cmd/main.go -r=12 -g=13 -b=14 -f=input/sample.txt

  data:
    cmds:
      - go run cmd/main.go -r=12 -g=13 -b=14 -f=input/data.txt

  all:
    cmds:
      - task sample
      - task data
