version: "3"

tasks:
  test:
    cmds:
      - go test ./...

  part1:
    cmds:
      - go run cmd/validate/main.go -r=12 -g=13 -b=14 -f=input/sample.txt
      - go run cmd/validate/main.go -r=12 -g=13 -b=14 -f=input/data.txt

  part2:
    cmds:
      - go run cmd/calculate/main.go -f=input/sample.txt
      - go run cmd/calculate/main.go -f=input/data.txt

  all:
    cmds:
      - task part1
      - task part2
